#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

echo "Copying initial conditions into place"
\rm -rf 0
cp -r 0.org 0 > /dev/null 2>&1

runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
